#############################################################################
# Makefile for building: graph-constructor
# Generated by qmake (3.1) (Qt 6.8.0)
# Project:  GraphDocumentDevKit.pro
# Template: app
# Command: /home/max/projects/GraphDocumentDevKit/local_qt/6.8.0/gcc_64/bin/qmake -o Makefile GraphDocumentDevKit.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_OPENGL_LIB -DQT_SVG_LIB -DQT_GUI_LIB -DQT_QMLMETA_LIB -DQT_QMLMODELS_LIB -DQT_QMLWORKERSCRIPT_LIB -DQT_QML_LIB -DQT_QMLINTEGRATION_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -fPIC -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++2a -Wall -Wextra -fPIC -D_REENTRANT $(DEFINES)
INCPATH       = -I. -Iinclude -Ilocal_qt/6.8.0/gcc_64/include -Ilocal_qt/6.8.0/gcc_64/include/QtQuick -Ilocal_qt/6.8.0/gcc_64/include/QtOpenGL -Ilocal_qt/6.8.0/gcc_64/include/QtSvg -Ilocal_qt/6.8.0/gcc_64/include/QtGui -Ilocal_qt/6.8.0/gcc_64/include/QtQmlMeta -Ilocal_qt/6.8.0/gcc_64/include/QtQmlModels -Ilocal_qt/6.8.0/gcc_64/include/QtQmlWorkerScript -Ilocal_qt/6.8.0/gcc_64/include/QtQml -Ilocal_qt/6.8.0/gcc_64/include/QtQmlIntegration -Ilocal_qt/6.8.0/gcc_64/include/QtNetwork -Ilocal_qt/6.8.0/gcc_64/include/QtCore -Ibuild/moc -Ilocal_qt/6.8.0/gcc_64/mkspecs/linux-g++
QMAKE         = /home/max/projects/GraphDocumentDevKit/local_qt/6.8.0/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/max/projects/GraphDocumentDevKit/local_qt/6.8.0/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/max/projects/GraphDocumentDevKit/local_qt/6.8.0/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = graph-constructor1.0.0
DISTDIR = /home/max/projects/GraphDocumentDevKit/build/obj/graph-constructor1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/max/projects/GraphDocumentDevKit/local_qt/6.8.0/gcc_64/lib -Wl,-rpath-link,/home/max/projects/GraphDocumentDevKit/local_qt/6.8.0/gcc_64/lib
LIBS          = $(SUBLIBS) /home/max/projects/GraphDocumentDevKit/local_qt/6.8.0/gcc_64/lib/libQt6Quick.so /home/max/projects/GraphDocumentDevKit/local_qt/6.8.0/gcc_64/lib/libQt6OpenGL.so /home/max/projects/GraphDocumentDevKit/local_qt/6.8.0/gcc_64/lib/libQt6Svg.so /home/max/projects/GraphDocumentDevKit/local_qt/6.8.0/gcc_64/lib/libQt6Gui.so /home/max/projects/GraphDocumentDevKit/local_qt/6.8.0/gcc_64/lib/libQt6QmlMeta.so /home/max/projects/GraphDocumentDevKit/local_qt/6.8.0/gcc_64/lib/libQt6QmlModels.so /home/max/projects/GraphDocumentDevKit/local_qt/6.8.0/gcc_64/lib/libQt6QmlWorkerScript.so /home/max/projects/GraphDocumentDevKit/local_qt/6.8.0/gcc_64/lib/libQt6Qml.so -pthread /home/max/projects/GraphDocumentDevKit/local_qt/6.8.0/gcc_64/lib/libQt6Network.so /home/max/projects/GraphDocumentDevKit/local_qt/6.8.0/gcc_64/lib/libQt6Core.so -lpthread -lGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = build/obj/

####### Files

SOURCES       = main.cpp \
		src/graphcanvas.cpp \
		src/graphexamples.cpp \
		src/tikz_exporter.cpp \
		build/rcc/qrc_resources.cpp \
		build/moc/moc_graphcanvas.cpp
OBJECTS       = build/obj/main.o \
		build/obj/graphcanvas.o \
		build/obj/graphexamples.o \
		build/obj/tikz_exporter.o \
		build/obj/qrc_resources.o \
		build/obj/moc_graphcanvas.o
DIST          = local_qt/6.8.0/gcc_64/mkspecs/features/spec_pre.prf \
		local_qt/6.8.0/gcc_64/mkspecs/common/unix.conf \
		local_qt/6.8.0/gcc_64/mkspecs/common/linux.conf \
		local_qt/6.8.0/gcc_64/mkspecs/common/sanitize.conf \
		local_qt/6.8.0/gcc_64/mkspecs/common/gcc-base.conf \
		local_qt/6.8.0/gcc_64/mkspecs/common/gcc-base-unix.conf \
		local_qt/6.8.0/gcc_64/mkspecs/common/g++-base.conf \
		local_qt/6.8.0/gcc_64/mkspecs/common/g++-unix.conf \
		local_qt/6.8.0/gcc_64/mkspecs/qconfig.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_ext_libjpeg.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_ext_libpng.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_core.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_example_icons_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_help.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_jpeg_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_labsanimation.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_labsanimation_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_labsplatform.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_labsplatform_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_labssettings.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_labssettings_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_labssharedimage.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_linguist.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_network.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_openglwidgets.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_png_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlassetdownloader.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlcompiler.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlcore.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlcore_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmldom_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlintegration.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlls_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlmeta.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlmeta_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlnetwork.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickeffects_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quicklayouts.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickvectorimage.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickvectorimage_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_svgwidgets.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_tools_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/features/qt_functions.prf \
		local_qt/6.8.0/gcc_64/mkspecs/features/qt_config.prf \
		local_qt/6.8.0/gcc_64/mkspecs/linux-g++/qmake.conf \
		local_qt/6.8.0/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		local_qt/6.8.0/gcc_64/mkspecs/features/exclusive_builds.prf \
		local_qt/6.8.0/gcc_64/mkspecs/features/toolchain.prf \
		local_qt/6.8.0/gcc_64/mkspecs/features/default_pre.prf \
		local_qt/6.8.0/gcc_64/mkspecs/features/resolve_config.prf \
		local_qt/6.8.0/gcc_64/mkspecs/features/default_post.prf \
		local_qt/6.8.0/gcc_64/mkspecs/features/warn_on.prf \
		local_qt/6.8.0/gcc_64/mkspecs/features/permissions.prf \
		local_qt/6.8.0/gcc_64/mkspecs/features/qt.prf \
		local_qt/6.8.0/gcc_64/mkspecs/features/resources_functions.prf \
		local_qt/6.8.0/gcc_64/mkspecs/features/resources.prf \
		local_qt/6.8.0/gcc_64/mkspecs/features/moc.prf \
		local_qt/6.8.0/gcc_64/mkspecs/features/unix/opengl.prf \
		local_qt/6.8.0/gcc_64/mkspecs/features/unix/thread.prf \
		local_qt/6.8.0/gcc_64/mkspecs/features/qmake_use.prf \
		local_qt/6.8.0/gcc_64/mkspecs/features/file_copies.prf \
		local_qt/6.8.0/gcc_64/mkspecs/features/testcase_targets.prf \
		local_qt/6.8.0/gcc_64/mkspecs/features/exceptions.prf \
		local_qt/6.8.0/gcc_64/mkspecs/features/yacc.prf \
		local_qt/6.8.0/gcc_64/mkspecs/features/lex.prf \
		GraphDocumentDevKit.pro include/graphcanvas.h \
		include/tikz_exporter.h main.cpp \
		src/graphcanvas.cpp \
		src/tikz_exporter.cpp
QMAKE_TARGET  = graph-constructor
DESTDIR       = 
TARGET        = graph-constructor


first: all
####### Build rules

graph-constructor:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: GraphDocumentDevKit.pro local_qt/6.8.0/gcc_64/mkspecs/linux-g++/qmake.conf local_qt/6.8.0/gcc_64/mkspecs/features/spec_pre.prf \
		local_qt/6.8.0/gcc_64/mkspecs/common/unix.conf \
		local_qt/6.8.0/gcc_64/mkspecs/common/linux.conf \
		local_qt/6.8.0/gcc_64/mkspecs/common/sanitize.conf \
		local_qt/6.8.0/gcc_64/mkspecs/common/gcc-base.conf \
		local_qt/6.8.0/gcc_64/mkspecs/common/gcc-base-unix.conf \
		local_qt/6.8.0/gcc_64/mkspecs/common/g++-base.conf \
		local_qt/6.8.0/gcc_64/mkspecs/common/g++-unix.conf \
		local_qt/6.8.0/gcc_64/mkspecs/qconfig.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_ext_libjpeg.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_ext_libpng.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_core.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_example_icons_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_help.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_jpeg_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_labsanimation.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_labsanimation_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_labsplatform.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_labsplatform_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_labssettings.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_labssettings_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_labssharedimage.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_linguist.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_network.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_openglwidgets.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_png_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlassetdownloader.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlcompiler.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlcore.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlcore_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmldom_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlintegration.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlls_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlmeta.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlmeta_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlnetwork.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickeffects_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quicklayouts.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickvectorimage.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickvectorimage_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_svgwidgets.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_tools_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		local_qt/6.8.0/gcc_64/mkspecs/features/qt_functions.prf \
		local_qt/6.8.0/gcc_64/mkspecs/features/qt_config.prf \
		local_qt/6.8.0/gcc_64/mkspecs/linux-g++/qmake.conf \
		local_qt/6.8.0/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		local_qt/6.8.0/gcc_64/mkspecs/features/exclusive_builds.prf \
		local_qt/6.8.0/gcc_64/mkspecs/features/toolchain.prf \
		local_qt/6.8.0/gcc_64/mkspecs/features/default_pre.prf \
		local_qt/6.8.0/gcc_64/mkspecs/features/resolve_config.prf \
		local_qt/6.8.0/gcc_64/mkspecs/features/default_post.prf \
		local_qt/6.8.0/gcc_64/mkspecs/features/warn_on.prf \
		local_qt/6.8.0/gcc_64/mkspecs/features/permissions.prf \
		local_qt/6.8.0/gcc_64/mkspecs/features/qt.prf \
		local_qt/6.8.0/gcc_64/mkspecs/features/resources_functions.prf \
		local_qt/6.8.0/gcc_64/mkspecs/features/resources.prf \
		local_qt/6.8.0/gcc_64/mkspecs/features/moc.prf \
		local_qt/6.8.0/gcc_64/mkspecs/features/unix/opengl.prf \
		local_qt/6.8.0/gcc_64/mkspecs/features/unix/thread.prf \
		local_qt/6.8.0/gcc_64/mkspecs/features/qmake_use.prf \
		local_qt/6.8.0/gcc_64/mkspecs/features/file_copies.prf \
		local_qt/6.8.0/gcc_64/mkspecs/features/testcase_targets.prf \
		local_qt/6.8.0/gcc_64/mkspecs/features/exceptions.prf \
		local_qt/6.8.0/gcc_64/mkspecs/features/yacc.prf \
		local_qt/6.8.0/gcc_64/mkspecs/features/lex.prf \
		GraphDocumentDevKit.pro \
		resources/resources.qrc \
		local_qt/6.8.0/gcc_64/lib/libQt6Quick.prl \
		local_qt/6.8.0/gcc_64/lib/libQt6OpenGL.prl \
		local_qt/6.8.0/gcc_64/lib/libQt6Svg.prl \
		local_qt/6.8.0/gcc_64/lib/libQt6Gui.prl \
		local_qt/6.8.0/gcc_64/lib/libQt6QmlMeta.prl \
		local_qt/6.8.0/gcc_64/lib/libQt6QmlModels.prl \
		local_qt/6.8.0/gcc_64/lib/libQt6QmlWorkerScript.prl \
		local_qt/6.8.0/gcc_64/lib/libQt6Qml.prl \
		local_qt/6.8.0/gcc_64/lib/libQt6Network.prl \
		local_qt/6.8.0/gcc_64/lib/libQt6Core.prl
	$(QMAKE) -o Makefile GraphDocumentDevKit.pro
local_qt/6.8.0/gcc_64/mkspecs/features/spec_pre.prf:
local_qt/6.8.0/gcc_64/mkspecs/common/unix.conf:
local_qt/6.8.0/gcc_64/mkspecs/common/linux.conf:
local_qt/6.8.0/gcc_64/mkspecs/common/sanitize.conf:
local_qt/6.8.0/gcc_64/mkspecs/common/gcc-base.conf:
local_qt/6.8.0/gcc_64/mkspecs/common/gcc-base-unix.conf:
local_qt/6.8.0/gcc_64/mkspecs/common/g++-base.conf:
local_qt/6.8.0/gcc_64/mkspecs/common/g++-unix.conf:
local_qt/6.8.0/gcc_64/mkspecs/qconfig.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_ext_libjpeg.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_ext_libpng.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_core.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_designer.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_example_icons_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_gui.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_harfbuzz_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_help.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_jpeg_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_labsanimation.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_labsanimation_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_labsplatform.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_labsplatform_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_labssettings.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_labssettings_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_labssharedimage.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_labssharedimage_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_linguist.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_network.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_openglwidgets.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_openglwidgets_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_png_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qdoccatch_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qml.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlassetdownloader.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlcompiler.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlcore.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlcore_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmldom_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlintegration.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlintegration_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlls_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlmeta.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlmeta_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlnetwork.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlnetwork_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quick.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basic.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusion.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imagine.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2material.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2material_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universal.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickeffects_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quicklayouts.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quicklayouts_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickvectorimage.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickvectorimage_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_sql.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_svg.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_svgwidgets.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_svgwidgets_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_tools_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_waylandglobal_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_wl_shell_integration_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_xml.pri:
local_qt/6.8.0/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
local_qt/6.8.0/gcc_64/mkspecs/features/qt_functions.prf:
local_qt/6.8.0/gcc_64/mkspecs/features/qt_config.prf:
local_qt/6.8.0/gcc_64/mkspecs/linux-g++/qmake.conf:
local_qt/6.8.0/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
local_qt/6.8.0/gcc_64/mkspecs/features/exclusive_builds.prf:
local_qt/6.8.0/gcc_64/mkspecs/features/toolchain.prf:
local_qt/6.8.0/gcc_64/mkspecs/features/default_pre.prf:
local_qt/6.8.0/gcc_64/mkspecs/features/resolve_config.prf:
local_qt/6.8.0/gcc_64/mkspecs/features/default_post.prf:
local_qt/6.8.0/gcc_64/mkspecs/features/warn_on.prf:
local_qt/6.8.0/gcc_64/mkspecs/features/permissions.prf:
local_qt/6.8.0/gcc_64/mkspecs/features/qt.prf:
local_qt/6.8.0/gcc_64/mkspecs/features/resources_functions.prf:
local_qt/6.8.0/gcc_64/mkspecs/features/resources.prf:
local_qt/6.8.0/gcc_64/mkspecs/features/moc.prf:
local_qt/6.8.0/gcc_64/mkspecs/features/unix/opengl.prf:
local_qt/6.8.0/gcc_64/mkspecs/features/unix/thread.prf:
local_qt/6.8.0/gcc_64/mkspecs/features/qmake_use.prf:
local_qt/6.8.0/gcc_64/mkspecs/features/file_copies.prf:
local_qt/6.8.0/gcc_64/mkspecs/features/testcase_targets.prf:
local_qt/6.8.0/gcc_64/mkspecs/features/exceptions.prf:
local_qt/6.8.0/gcc_64/mkspecs/features/yacc.prf:
local_qt/6.8.0/gcc_64/mkspecs/features/lex.prf:
GraphDocumentDevKit.pro:
resources/resources.qrc:
local_qt/6.8.0/gcc_64/lib/libQt6Quick.prl:
local_qt/6.8.0/gcc_64/lib/libQt6OpenGL.prl:
local_qt/6.8.0/gcc_64/lib/libQt6Svg.prl:
local_qt/6.8.0/gcc_64/lib/libQt6Gui.prl:
local_qt/6.8.0/gcc_64/lib/libQt6QmlMeta.prl:
local_qt/6.8.0/gcc_64/lib/libQt6QmlModels.prl:
local_qt/6.8.0/gcc_64/lib/libQt6QmlWorkerScript.prl:
local_qt/6.8.0/gcc_64/lib/libQt6Qml.prl:
local_qt/6.8.0/gcc_64/lib/libQt6Network.prl:
local_qt/6.8.0/gcc_64/lib/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile GraphDocumentDevKit.pro

qmake_all: FORCE


all: Makefile graph-constructor

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources/resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents local_qt/6.8.0/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents include/graphcanvas.h include/tikz_exporter.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp src/graphcanvas.cpp src/tikz_exporter.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: build/rcc/qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) build/rcc/qrc_resources.cpp
build/rcc/qrc_resources.cpp: resources/resources.qrc \
		local_qt/6.8.0/gcc_64/libexec/rcc \
		resources/main.qml
	/home/max/projects/GraphDocumentDevKit/local_qt/6.8.0/gcc_64/libexec/rcc -name resources resources/resources.qrc -o build/rcc/qrc_resources.cpp

compiler_moc_predefs_make_all: build/moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) build/moc/moc_predefs.h
build/moc/moc_predefs.h: local_qt/6.8.0/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++2a -Wall -Wextra -fPIC -dM -E -o build/moc/moc_predefs.h local_qt/6.8.0/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: build/moc/moc_graphcanvas.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc/moc_graphcanvas.cpp
build/moc/moc_graphcanvas.cpp: include/graphcanvas.h \
		local_qt/6.8.0/gcc_64/include/QtQuick/QQuickPaintedItem \
		local_qt/6.8.0/gcc_64/include/QtQuick/qquickpainteditem.h \
		local_qt/6.8.0/gcc_64/include/QtQuick/qquickitem.h \
		local_qt/6.8.0/gcc_64/include/QtQuick/qtquickglobal.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qtqmlglobal.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qglobal.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtversionchecks.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtconfiginclude.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qconfig.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtcore-config.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtconfigmacros.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtdeprecationdefinitions.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtcoreexports.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qcompilerdetection.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qprocessordetection.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qsystemdetection.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtdeprecationmarkers.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtclasshelpermacros.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtpreprocessorsupport.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qassert.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtnoop.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtypes.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtversion.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtypeinfo.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qcontainerfwd.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qsysinfo.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qlogging.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qflags.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qcompare_impl.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qatomic.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qbasicatomic.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qgenericatomic.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qyieldcpu.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qconstructormacros.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qdarwinhelpers.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qexceptionhandling.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qforeach.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qttypetraits.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qfunctionpointer.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qglobalstatic.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qmalloc.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qminmax.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qnumeric.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qoverload.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qswap.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtenvironmentvariables.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtresource.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qttranslation.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qversiontagging.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qtqml-config.h \
		local_qt/6.8.0/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		local_qt/6.8.0/gcc_64/include/QtNetwork/qtnetwork-config.h \
		local_qt/6.8.0/gcc_64/include/QtNetwork/qtnetworkexports.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qtqmlexports.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qtguiglobal.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qtgui-config.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qtguiexports.h \
		local_qt/6.8.0/gcc_64/include/QtQuick/qtquick-config.h \
		local_qt/6.8.0/gcc_64/include/QtQuick/qtquickexports.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qqml.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qqmlprivate.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qjsprimitivevalue.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qjsnumbercoercion.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qstring.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qchar.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qcompare.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qcomparehelpers.h \
		local_qt/6.8.0/gcc_64/include/QtCore/q20type_traits.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qstringview.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qbytearray.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qrefcount.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qnamespace.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtmetamacros.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qarraydata.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qpair.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qarraydatapointer.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qarraydataops.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qcontainertools_impl.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qxptype_traits.h \
		local_qt/6.8.0/gcc_64/include/QtCore/q20functional.h \
		local_qt/6.8.0/gcc_64/include/QtCore/q20memory.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qbytearrayalgorithms.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qbytearrayview.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qstringfwd.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qstringliteral.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qstringalgorithms.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qlatin1stringview.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qanystringview.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qutf8stringview.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qstringtokenizer.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qstringbuilder.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qstringconverter.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qstringconverter_base.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qvariant.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qmetatype.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qdatastream.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qscopedpointer.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qiodevicebase.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qfloat16.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qhashfunctions.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qmath.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qalgorithms.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qiterable.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qmetacontainer.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qcontainerinfo.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtaggedpointer.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qobjectdefs.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qfunctionaltools_impl.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qscopeguard.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qdebug.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtextstream.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qcontiguouscache.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qsharedpointer.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qshareddata.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qsharedpointer_impl.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qlist.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qiterator.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qbytearraylist.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qstringlist.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qstringmatcher.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qmap.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qshareddata_impl.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qset.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qhash.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qvarlengtharray.h \
		local_qt/6.8.0/gcc_64/include/QtCore/q23utility.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qobject.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qcoreevent.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qobject_impl.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qbindingstorage.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qjsvalue.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qqmllist.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qqmlparserstatus.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qqmlpropertyvaluesource.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qdatetime.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qcalendar.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qlocale.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qmetaobject.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qpointer.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qurl.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qversionnumber.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qspan.h \
		local_qt/6.8.0/gcc_64/include/QtCore/q20iterator.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtyperevision.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qqmlregistration.h \
		local_qt/6.8.0/gcc_64/include/QtQmlIntegration/qqmlintegration.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qqmlcomponent.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qqmlerror.h \
		local_qt/6.8.0/gcc_64/include/QtCore/QObject \
		local_qt/6.8.0/gcc_64/include/QtCore/QList \
		local_qt/6.8.0/gcc_64/include/QtCore/qproperty.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qpropertyprivate.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qevent.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qiodevice.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qeventpoint.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qvector2d.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qvectornd.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qpoint.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qrect.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qmargins.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qsize.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qpointingdevice.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qinputdevice.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qscreen.h \
		local_qt/6.8.0/gcc_64/include/QtCore/QRect \
		local_qt/6.8.0/gcc_64/include/QtCore/QSize \
		local_qt/6.8.0/gcc_64/include/QtCore/QSizeF \
		local_qt/6.8.0/gcc_64/include/QtGui/QTransform \
		local_qt/6.8.0/gcc_64/include/QtGui/qtransform.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qpolygon.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qregion.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qwindowdefs.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qline.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qnativeinterface.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qscreen_platform.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qguiapplication.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qcoreapplication.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qdeadlinetimer.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qelapsedtimer.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qeventloop.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qcoreapplication_platform.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qfuture.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qfutureinterface.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qmutex.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtsan_impl.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qresultstore.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qfuture_impl.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qthreadpool.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qthread.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qrunnable.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qexception.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qpromise.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qinputmethod.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qguiapplication_platform.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qkeysequence.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qfont.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qendian.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qaccessible.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qcolor.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qrgb.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qrgba64.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qaccessible_base.h \
		include/entt/entt.hpp \
		local_qt/6.8.0/gcc_64/include/QtGui/QColor \
		build/moc/moc_predefs.h \
		local_qt/6.8.0/gcc_64/libexec/moc
	/home/max/projects/GraphDocumentDevKit/local_qt/6.8.0/gcc_64/libexec/moc $(DEFINES) --include /home/max/projects/GraphDocumentDevKit/build/moc/moc_predefs.h -I/home/max/projects/GraphDocumentDevKit/local_qt/6.8.0/gcc_64/mkspecs/linux-g++ -I/home/max/projects/GraphDocumentDevKit -I/home/max/projects/GraphDocumentDevKit/include -I/home/max/projects/GraphDocumentDevKit/local_qt/6.8.0/gcc_64/include -I/home/max/projects/GraphDocumentDevKit/local_qt/6.8.0/gcc_64/include/QtQuick -I/home/max/projects/GraphDocumentDevKit/local_qt/6.8.0/gcc_64/include/QtOpenGL -I/home/max/projects/GraphDocumentDevKit/local_qt/6.8.0/gcc_64/include/QtSvg -I/home/max/projects/GraphDocumentDevKit/local_qt/6.8.0/gcc_64/include/QtGui -I/home/max/projects/GraphDocumentDevKit/local_qt/6.8.0/gcc_64/include/QtQmlMeta -I/home/max/projects/GraphDocumentDevKit/local_qt/6.8.0/gcc_64/include/QtQmlModels -I/home/max/projects/GraphDocumentDevKit/local_qt/6.8.0/gcc_64/include/QtQmlWorkerScript -I/home/max/projects/GraphDocumentDevKit/local_qt/6.8.0/gcc_64/include/QtQml -I/home/max/projects/GraphDocumentDevKit/local_qt/6.8.0/gcc_64/include/QtQmlIntegration -I/home/max/projects/GraphDocumentDevKit/local_qt/6.8.0/gcc_64/include/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/graphcanvas.h -o build/moc/moc_graphcanvas.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

build/obj/main.o: main.cpp local_qt/6.8.0/gcc_64/include/QtGui/QGuiApplication \
		local_qt/6.8.0/gcc_64/include/QtGui/qguiapplication.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qtguiglobal.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qglobal.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtversionchecks.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtconfiginclude.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qconfig.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtcore-config.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtconfigmacros.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtdeprecationdefinitions.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtcoreexports.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qcompilerdetection.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qprocessordetection.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qsystemdetection.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtdeprecationmarkers.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtclasshelpermacros.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtpreprocessorsupport.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qassert.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtnoop.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtypes.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtversion.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtypeinfo.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qcontainerfwd.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qsysinfo.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qlogging.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qflags.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qcompare_impl.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qatomic.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qbasicatomic.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qgenericatomic.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qyieldcpu.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qconstructormacros.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qdarwinhelpers.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qexceptionhandling.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qforeach.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qttypetraits.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qfunctionpointer.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qglobalstatic.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qmalloc.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qminmax.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qnumeric.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qoverload.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qswap.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtenvironmentvariables.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtresource.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qttranslation.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qversiontagging.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qtgui-config.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qtguiexports.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qcoreapplication.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qstring.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qchar.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qcompare.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qcomparehelpers.h \
		local_qt/6.8.0/gcc_64/include/QtCore/q20type_traits.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qstringview.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qbytearray.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qrefcount.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qnamespace.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtmetamacros.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qarraydata.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qpair.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qarraydatapointer.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qarraydataops.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qcontainertools_impl.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qxptype_traits.h \
		local_qt/6.8.0/gcc_64/include/QtCore/q20functional.h \
		local_qt/6.8.0/gcc_64/include/QtCore/q20memory.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qbytearrayalgorithms.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qbytearrayview.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qstringfwd.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qstringliteral.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qstringalgorithms.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qlatin1stringview.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qanystringview.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qutf8stringview.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qstringtokenizer.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qstringbuilder.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qstringconverter.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qstringconverter_base.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qcoreevent.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qobjectdefs.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qfunctionaltools_impl.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qdeadlinetimer.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qelapsedtimer.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qmetatype.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qdatastream.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qscopedpointer.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qiodevicebase.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qfloat16.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qhashfunctions.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qmath.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qalgorithms.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qiterable.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qmetacontainer.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qcontainerinfo.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtaggedpointer.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qscopeguard.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qeventloop.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qobject.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qlist.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qiterator.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qbytearraylist.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qstringlist.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qstringmatcher.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qobject_impl.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qbindingstorage.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qnativeinterface.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qdebug.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtextstream.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qcontiguouscache.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qsharedpointer.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qshareddata.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qsharedpointer_impl.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qmap.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qshareddata_impl.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qset.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qhash.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qvarlengtharray.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qcoreapplication_platform.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qfuture.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qfutureinterface.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qmutex.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtsan_impl.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qresultstore.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qfuture_impl.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qthreadpool.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qthread.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qrunnable.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qexception.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qpromise.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qvariant.h \
		local_qt/6.8.0/gcc_64/include/QtCore/q23utility.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qwindowdefs.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qinputmethod.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qlocale.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qpoint.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qsize.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qmargins.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qguiapplication_platform.h \
		local_qt/6.8.0/gcc_64/include/QtQml/QQmlApplicationEngine \
		local_qt/6.8.0/gcc_64/include/QtQml/qqmlapplicationengine.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qqmlengine.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qurl.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qjsengine.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtimezone.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qdatetime.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qcalendar.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qjsvalue.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qtqmlglobal.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qtqml-config.h \
		local_qt/6.8.0/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		local_qt/6.8.0/gcc_64/include/QtNetwork/qtnetwork-config.h \
		local_qt/6.8.0/gcc_64/include/QtNetwork/qtnetworkexports.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qtqmlexports.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qjsmanagedvalue.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qjsprimitivevalue.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qjsnumbercoercion.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qqmldebug.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qqml.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qqmlprivate.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qqmllist.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qqmlparserstatus.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qqmlpropertyvaluesource.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qmetaobject.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qpointer.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qversionnumber.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qspan.h \
		local_qt/6.8.0/gcc_64/include/QtCore/q20iterator.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtyperevision.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qqmlregistration.h \
		local_qt/6.8.0/gcc_64/include/QtQmlIntegration/qqmlintegration.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qqmlerror.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qqmlabstracturlinterceptor.h \
		local_qt/6.8.0/gcc_64/include/QtQml/QQmlContext \
		local_qt/6.8.0/gcc_64/include/QtQml/qqmlcontext.h \
		include/graphcanvas.h \
		local_qt/6.8.0/gcc_64/include/QtQuick/QQuickPaintedItem \
		local_qt/6.8.0/gcc_64/include/QtQuick/qquickpainteditem.h \
		local_qt/6.8.0/gcc_64/include/QtQuick/qquickitem.h \
		local_qt/6.8.0/gcc_64/include/QtQuick/qtquickglobal.h \
		local_qt/6.8.0/gcc_64/include/QtQuick/qtquick-config.h \
		local_qt/6.8.0/gcc_64/include/QtQuick/qtquickexports.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qqmlcomponent.h \
		local_qt/6.8.0/gcc_64/include/QtCore/QObject \
		local_qt/6.8.0/gcc_64/include/QtCore/QList \
		local_qt/6.8.0/gcc_64/include/QtCore/qproperty.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qpropertyprivate.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qevent.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qiodevice.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qeventpoint.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qvector2d.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qvectornd.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qrect.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qpointingdevice.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qinputdevice.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qscreen.h \
		local_qt/6.8.0/gcc_64/include/QtCore/QRect \
		local_qt/6.8.0/gcc_64/include/QtCore/QSize \
		local_qt/6.8.0/gcc_64/include/QtCore/QSizeF \
		local_qt/6.8.0/gcc_64/include/QtGui/QTransform \
		local_qt/6.8.0/gcc_64/include/QtGui/qtransform.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qpolygon.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qregion.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qline.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qscreen_platform.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qkeysequence.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qfont.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qendian.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qaccessible.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qcolor.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qrgb.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qrgba64.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qaccessible_base.h \
		include/entt/entt.hpp \
		local_qt/6.8.0/gcc_64/include/QtGui/QColor
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/main.o main.cpp

build/obj/graphcanvas.o: src/graphcanvas.cpp include/graphcanvas.h \
		include/tikz_exporter.h \
		include/graphexamples.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/graphcanvas.o src/graphcanvas.cpp

build/obj/graphexamples.o: src/graphexamples.cpp include/graphexamples.h \
		include/graphcanvas.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/graphexamples.o src/graphexamples.cpp

build/obj/tikz_exporter.o: src/tikz_exporter.cpp include/tikz_exporter.h \
		include/entt/entt.hpp \
		include/graphcanvas.h \
		local_qt/6.8.0/gcc_64/include/QtQuick/QQuickPaintedItem \
		local_qt/6.8.0/gcc_64/include/QtQuick/qquickpainteditem.h \
		local_qt/6.8.0/gcc_64/include/QtQuick/qquickitem.h \
		local_qt/6.8.0/gcc_64/include/QtQuick/qtquickglobal.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qtqmlglobal.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qglobal.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtversionchecks.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtconfiginclude.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qconfig.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtcore-config.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtconfigmacros.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtdeprecationdefinitions.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtcoreexports.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qcompilerdetection.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qprocessordetection.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qsystemdetection.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtdeprecationmarkers.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtclasshelpermacros.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtpreprocessorsupport.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qassert.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtnoop.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtypes.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtversion.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtypeinfo.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qcontainerfwd.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qsysinfo.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qlogging.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qflags.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qcompare_impl.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qatomic.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qbasicatomic.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qgenericatomic.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qyieldcpu.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qconstructormacros.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qdarwinhelpers.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qexceptionhandling.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qforeach.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qttypetraits.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qfunctionpointer.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qglobalstatic.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qmalloc.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qminmax.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qnumeric.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qoverload.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qswap.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtenvironmentvariables.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtresource.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qttranslation.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qversiontagging.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qtqml-config.h \
		local_qt/6.8.0/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		local_qt/6.8.0/gcc_64/include/QtNetwork/qtnetwork-config.h \
		local_qt/6.8.0/gcc_64/include/QtNetwork/qtnetworkexports.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qtqmlexports.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qtguiglobal.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qtgui-config.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qtguiexports.h \
		local_qt/6.8.0/gcc_64/include/QtQuick/qtquick-config.h \
		local_qt/6.8.0/gcc_64/include/QtQuick/qtquickexports.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qqml.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qqmlprivate.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qjsprimitivevalue.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qjsnumbercoercion.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qstring.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qchar.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qcompare.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qcomparehelpers.h \
		local_qt/6.8.0/gcc_64/include/QtCore/q20type_traits.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qstringview.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qbytearray.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qrefcount.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qnamespace.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtmetamacros.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qarraydata.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qpair.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qarraydatapointer.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qarraydataops.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qcontainertools_impl.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qxptype_traits.h \
		local_qt/6.8.0/gcc_64/include/QtCore/q20functional.h \
		local_qt/6.8.0/gcc_64/include/QtCore/q20memory.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qbytearrayalgorithms.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qbytearrayview.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qstringfwd.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qstringliteral.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qstringalgorithms.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qlatin1stringview.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qanystringview.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qutf8stringview.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qstringtokenizer.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qstringbuilder.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qstringconverter.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qstringconverter_base.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qvariant.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qmetatype.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qdatastream.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qscopedpointer.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qiodevicebase.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qfloat16.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qhashfunctions.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qmath.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qalgorithms.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qiterable.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qmetacontainer.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qcontainerinfo.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtaggedpointer.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qobjectdefs.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qfunctionaltools_impl.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qscopeguard.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qdebug.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtextstream.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qcontiguouscache.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qsharedpointer.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qshareddata.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qsharedpointer_impl.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qlist.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qiterator.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qbytearraylist.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qstringlist.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qstringmatcher.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qmap.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qshareddata_impl.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qset.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qhash.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qvarlengtharray.h \
		local_qt/6.8.0/gcc_64/include/QtCore/q23utility.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qobject.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qcoreevent.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qobject_impl.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qbindingstorage.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qjsvalue.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qqmllist.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qqmlparserstatus.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qqmlpropertyvaluesource.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qdatetime.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qcalendar.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qlocale.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qmetaobject.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qpointer.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qurl.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qversionnumber.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qspan.h \
		local_qt/6.8.0/gcc_64/include/QtCore/q20iterator.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtyperevision.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qqmlregistration.h \
		local_qt/6.8.0/gcc_64/include/QtQmlIntegration/qqmlintegration.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qqmlcomponent.h \
		local_qt/6.8.0/gcc_64/include/QtQml/qqmlerror.h \
		local_qt/6.8.0/gcc_64/include/QtCore/QObject \
		local_qt/6.8.0/gcc_64/include/QtCore/QList \
		local_qt/6.8.0/gcc_64/include/QtCore/qproperty.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qpropertyprivate.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qevent.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qiodevice.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qeventpoint.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qvector2d.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qvectornd.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qpoint.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qrect.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qmargins.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qsize.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qpointingdevice.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qinputdevice.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qscreen.h \
		local_qt/6.8.0/gcc_64/include/QtCore/QRect \
		local_qt/6.8.0/gcc_64/include/QtCore/QSize \
		local_qt/6.8.0/gcc_64/include/QtCore/QSizeF \
		local_qt/6.8.0/gcc_64/include/QtGui/QTransform \
		local_qt/6.8.0/gcc_64/include/QtGui/qtransform.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qpolygon.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qregion.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qwindowdefs.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qline.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qnativeinterface.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qscreen_platform.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qguiapplication.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qcoreapplication.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qdeadlinetimer.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qelapsedtimer.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qeventloop.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qcoreapplication_platform.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qfuture.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qfutureinterface.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qmutex.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qtsan_impl.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qresultstore.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qfuture_impl.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qthreadpool.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qthread.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qrunnable.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qexception.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qpromise.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qinputmethod.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qguiapplication_platform.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qkeysequence.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qfont.h \
		local_qt/6.8.0/gcc_64/include/QtCore/qendian.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qaccessible.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qcolor.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qrgb.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qrgba64.h \
		local_qt/6.8.0/gcc_64/include/QtGui/qaccessible_base.h \
		local_qt/6.8.0/gcc_64/include/QtGui/QColor
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/tikz_exporter.o src/tikz_exporter.cpp

build/obj/qrc_resources.o: build/rcc/qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/qrc_resources.o build/rcc/qrc_resources.cpp

build/obj/moc_graphcanvas.o: build/moc/moc_graphcanvas.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_graphcanvas.o build/moc/moc_graphcanvas.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

.SUFFIXES:

